#-------------------------------------------
# SENSOR
#-------------------------------------------
sensor:
  - platform: adc
    pin: A0
    id: adc_A0    
    name: "adc_A0"
    update_interval: 1s
    filters:
      - multiply: 3.3
      
  - platform: sht3xd
    temperature:
      name: "Температура"
      icon: mdi:thermometer
    humidity:
      name: "Влажность"
      icon: mdi:water-percent
    address: 0x44
    update_interval: 60s

  - platform: ntc
    sensor: resistance_sensor
    calibration:
      b_constant: 3980
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: NTC Temperature
    icon: mdi:thermometer
    id: NTC_Temperature

  # Example source sensors:
  - platform: resistance
    id: resistance_sensor
    sensor: adc_A0
    configuration: UPSTREAM
    resistor: 4.5kOhm
    name: Resistance Sensor


# Example single-point configuration entry (for heating only)
climate:
  - platform: thermostat
    name: "Thermostat Controller"
    sensor: NTC_Temperature
    min_heating_off_time: 60s
    min_heating_run_time: 60s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: relay
    idle_action:
      - switch.turn_off: relay
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 20 °C
    visual:
      min_temperature: 18
      max_temperature: 36
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1

switch:
  - platform: gpio
    name: "Реле"
    pin: GPIO3
    id: relay