substitutions:
  espname: "rele-ujin"


esphome:
  name: $espname
  friendly_name: rele ujin

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "7NXk2xcRiFi57xDn1lUAQ2nS5C+aZ2oLp6/gjqQL+Yc="

ota:
  - platform: esphome
    password: "54bea113c3cd0aa64fc0750c7250b5fa"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rele-Ujin Fallback Hotspot"
    password: "3wWKhoZdznRo"

captive_portal:

mqtt:
  broker: "192.168.1.11"
  port: 1883
  username: !secret mqtt_login
  password: !secret mqtt_password

switch:
  - platform: gpio
    name: "Реле 1"
    pin: GPIO4
    id: relay1
    state_topic: "$espname/relay/relay1"
    command_topic: "$espname/relay/relay1/set"

  - platform: gpio
    name: "Реле 2"
    pin: GPIO5
    id: relay2
    state_topic: "$espname/relay/relay2"
    command_topic: "$espname/relay/relay2/set"

output:
  - platform: gpio
    pin: GPIO15
    id: gpio_15

  - platform: gpio
    pin: GPIO14
    id: gpio_14

  - platform: gpio
    pin: GPIO16
    id: gpio_16

light:
  - platform: binary
    name: "Настройка"
    output: gpio_15   
    id: led_setting
    state_topic: "$espname/led/setting"
    command_topic: "$espname/led/setting/set"

  - platform: binary
    output: gpio_14
    name: "Канал 1"
    id: led_channel1
    state_topic: "$espname/led/channel1"
    command_topic: "$espname/led/channel1/set"

  - platform: binary
    output: gpio_16
    name: "Канал 2"
    id: led_channel2  
    state_topic: "$espname/led/channel2"
    command_topic: "$espname/led/channel2/set"

binary_sensor:

  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: "Настройка"
#    device_class: window
    id: setting
    state_topic: "$espname/button/setting"

  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
    name: "Канал 1"
    id: channel1
    state_topic: "$espname/button/channel1"
    on_press:    
      - switch.toggle: relay1
      - light.toggle: led_channel1      

  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    name: "Канал 2"
    id: cannel2
    state_topic: "$espname/button/channel2"
    on_press:    
      - switch.toggle: relay2
      - light.toggle: led_channel2 

  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
    id: "input1"
    name: "Вход 1"
    state_topic: "$espname/input/input1"
    on_press:
      - switch.turn_on: relay1
      - light.turn_on: led_channel1      
    on_release:
      - switch.turn_off: relay1
      - light.turn_off: led_channel1

  - platform: template
    name: "Вход 2"
    id: input2
    lambda: return (id(button_adc).state < .5);
    state_topic: "$espname/input/input2"
    on_press:
      - switch.turn_on: relay2
      - light.turn_on: led_channel2      
    on_release:
      - switch.turn_off: relay2
      - light.turn_off: led_channel2


sensor:
  - platform: adc
    id: button_adc
    pin: A0
    update_interval: .3s

  - platform: uptime
    name: "Uptime"
    
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

     
  