#GPIO36 I  Датчик Холла                             #GPIO23 I/O 
#GPIO39 I                                           #GPIO22 I/O I2C SCL
#GPIO34 I GPIO34 PIR                                #GPIO3  I/O U0RXD Dimmer
#GPIO35 I                                           #GPIO1  I/O U0TXD Dimmer
#GPIO32 I/O Вход 1                                  #GPIO21 I/O I2C SDA
#GPIO33 I/O remote_receiver                         #GPIO19 I/O 
#GPIO25 I/O ir transmitter                          #GPIO18 I/O
#GPIO26 I/O LED                                     #GPIO5  I/O
#GPIO27 I/O off all i2c                             #17
#GPIO14 I/O CSS811 bh1750 ON LOW (HIGH OFF)         #16
#GPIO12 I/O                                         #GPIO4  I/O touch2 (s2) 
#GPIO13 I/O MP45DT02 I2S WS                         #GPIO2 ADC touch1(s1)
                                                    #GPIO15 I/O MP45DT02 I2S DOUT 
                                                    #GPIO0 Button

#####################################################################################
#9                                                  #8
#10                                                 #7
#11                                                 #6

#GPIO37 I SENSOR_CAPP
#GPIO38 I SENSOR_CAPN
#GPIO39 I Датчик Холла

#####################
#Pic     # pic uart #
#5в.     # Вх2      #
#3.3в    # pic uart #
#Gnd.    # Вх1      #
#####################

#get_setup_priority.baseline_
#set_baseline()

substitutions:
  name: lume-co2
  device_description: Lume Luxe wifi/BLE/IR/CO2
  light_1_device: light.kithen1
  light_2_device: light.kithen2
  sda_i2c: GPIO21
  scl_i2c: GPIO22
  beeper_ledc: GPIO12

esphome:
  name: "${name}"
  comment: "${device_description}"
  on_boot:
    - priority: 500
      then:
        - lambda:   
            pinMode(14, OUTPUT); 
            digitalWrite(14, LOW);      

api:
  reboot_timeout: 0s     
  
esp32:
  board: esp32dev
  framework:
    type: arduino
#-------------------------------------------
# PSRAM
#-------------------------------------------
psram:
  mode: quad
  speed: 80MHz

#-------------------------------------------
# I2c
#-------------------------------------------
i2c:
  sda: $sda_i2c
  scl: $scl_i2c
  scan: true

#-------------------------------------------
# PACKAGES
#-------------------------------------------
packages:
# обязательные пакеты
  wifi: !include packages/wifi.yaml
  web: !include included/web.yaml
  device_base: !include packages/device_base.yaml

# Диммер для теста !!!Не рабочий в этой версии!!!
  zero_dimm: !include 
    file: packages/lume/zero_dimm.yaml
    vars:
      dimmer1_zero: GPIO5 
      dimmer2_zero: GPIO5
      dimmer1_gate: GPIO19  
      dimmer2_gate: GPIO18  
      type_light1: monochromatic # binary
      type_light2: monochromatic # binary

# Сенсорные кнопки
  but: !include 
    file: packages/lume/button.yaml
    vars:
      one_butt: GPIO2
      two_butt: GPIO4

# не обязательные пакеты
 # time: !include included/time.yaml

# Температура ESP32
  esp32_temp: !include packages/sensor/esp32_temp.yaml

# Captive portal
#  cap: !include 
#    file: packages/lume/captive.yaml
#    vars:
#      ssid_captive: "Lume"
#      pass_captive: "12345678"

# ИК приемник
  ir_receiver: !include 
    file: packages/lume/ir_receiver.yaml
    vars:
      pin_ir_receiver: GPIO33

# ИК передатчик
  ir_transmitter: !include 
    file: packages/lume/ir_transmitter.yaml
    vars:
      pin_ir_transmitter: GPIO25

# Датчик освещености
  bh1750: !include
    file: packages/sensor/bh1750.yaml
    vars:
      id_bh: i_lume

# Датчик температуры и влажности 
 # sht3x: !include 
  #  file: packages/sensor/sht3x.yaml
  # vars:
   #   id_sht3x_t: sht3x_t
   #   id_sht3x_h: sht3x_h

# Датчик CO2
#  ccs811: !include 
#    file: packages/lume/ccs811.yaml
#    vars:
#      id_ccs811_t: sht3x_t
#      id_ccs811_h: sht3x_h
#      id_ccs811_eco2: ccs811_eco2
#      id_ccs811_tvoc: ccs811_tvoc

# Датчик температуры, влажности, CO2, давления, VOC, качества воздуха 
  bme680_bsec: !include 
    file: packages/sensor/bme680_bsec2.yaml
    vars:
      id_bme680_t: bme680_t
      id_bme680_h: bme680_h
      id_bme680_p: bme680_p
      id_bme680_iaq: bme680_iaq
      id_bme680_co2: bme680_co2
      id_bme680_voc: bme680_voc
      model_bme: bme688
      address_bme680: 0x76

# Подсведка кнопок
  led: !include 
    file: packages/lume/led_lume.yaml
    vars:
      led_lume_pin: GPIO26
      led_lume: 5

# Входы
  1in: !include 
    file: packages/lume/1in.yaml
    vars:
      one_pin: GPIO32

# Шумомер
  noise: !include 
    file: packages/lume/noise_pdm.yaml
    vars:
      noise_ws: GPIO13
      noise_din: GPIO15

# Датчик движения
  pir: !include 
    file: packages/lume/pir.yaml
    vars:
      pir_pin: GPIO34
      pir_addres: 0x28

#-------------------------------------------
# OUTPUT
#-------------------------------------------      
output:
  - platform: ledc
    pin: $beeper_ledc
    id: rtttl_out

#-------------------------------------------
# RTTTL
#-------------------------------------------
rtttl:
  output: rtttl_out
  gain: 60%

#-------------------------------------------
# SWITCH
#-------------------------------------------
switch:
  - platform: template
    name: "Звук нажатие клавиш"
    optimistic: True
    id: sound
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:volume-off



