substitutions:
  name: lume-co2
  device_description: Lume Luxe wifi/BLE/IR/CO2
  light_1_device: light.kithen1
  light_2_device: light.gyverlamp
  sda_i2c: GPIO21
  scl_i2c: GPIO22
  beeper_ledc: GPIO12

esphome:
  name: "${name}"
  comment: "${device_description}"
  on_boot:
    - priority: 500
      then:
        - lambda:   
            pinMode(14, OUTPUT); 
            digitalWrite(14, LOW);      

api:
  reboot_timeout: 0s     
  
esp32:
  board: esp32dev
  framework:
    type: arduino
#-------------------------------------------
# PSRAM
#-------------------------------------------
psram:
  mode: quad
  speed: 80MHz

#-------------------------------------------
# I2c
#-------------------------------------------
i2c:
  sda: $sda_i2c
  scl: $scl_i2c
  scan: true

#-------------------------------------------
# PACKAGES
#-------------------------------------------
packages:
# обязательные пакеты
  wifi: !include packages/wifi.yaml
  web: !include included/web.yaml
  device_base: !include packages/device_base.yaml

# Диммер 
#  zero_dimm: !include 
#    file: packages/ujin/dimm_ujin_uart.yaml
#    vars:


# Сенсорные кнопки
  but: !include 
    file: packages/ujin/button.yaml
    vars:
      one_butt: GPIO2
      two_butt: GPIO4
      touch_threshold: 1000 #1150
      delta_threshold: 5
      setup_threshold: false #true
      

# Температура ESP32
  esp32_temp: !include packages/esp32_temp.yaml

# Captive portal
#  cap: !include 
#    file: packages/captive.yaml
#    vars:
#      ssid_captive: "Lume"
#      pass_captive: "12345678"

# ИК приемник
  ir_receiver: !include 
    file: packages/ujin/sensor/ir_receiver.yaml
    vars:
      pin_ir_receiver: GPIO33

# ИК передатчик
  ir_transmitter: !include 
    file: packages/ujin/sensor/ir_transmitter.yaml
    vars:
      pin_ir_transmitter: GPIO25

# Датчик освещености
  bh1750: !include
    file: packages/ujin/sensor/bh1750.yaml
    vars:
      id_bh: i_lume

# Датчик температуры и влажности 
 # sht3x: !include 
  #  file: packages/ujin/sensor/sht3x.yaml
  # vars:
   #   id_sht3x_t: sht3x_t
   #   id_sht3x_h: sht3x_h

# Датчик CO2
#  ccs811: !include 
#    file: packages/ujin/sensor/ccs811.yaml
#    vars:
#      id_ccs811_t: sht3x_t
#      id_ccs811_h: sht3x_h
#      id_ccs811_eco2: ccs811_eco2
#      id_ccs811_tvoc: ccs811_tvoc

# Датчик температуры, влажности, CO2, давления, VOC, качества воздуха 
  bme680_bsec: !include 
    file: packages/ujin/sensor/bme680_bsec2.yaml
    vars:
      id_bme680_t: bme680_t
      id_bme680_h: bme680_h
      id_bme680_p: bme680_p
      id_bme680_iaq: bme680_iaq
      id_bme680_co2: bme680_co2
      id_bme680_voc: bme680_voc
      model_bme: bme688
      address_bme680: 0x76

# Подсветка кнопок
  led: !include 
    file: packages/ujin/led_lume.yaml
    vars:
      led_lume_pin: GPIO26
      led_lume: 5

# Входы
  1in: !include 
    file: packages/ujin/1in.yaml
    vars:
      one_pin: GPIO32

# Шумомер
  noise: !include 
    file: packages/ujin/sensor/noise_pdm.yaml
    vars:
      noise_ws: GPIO13
      noise_din: GPIO15

# Датчик движения
  pir: !include 
    file: packages/ujin/sensor/pir.yaml
    vars:
      pir_pin: GPIO34
      pir_addres: 0x28

#-------------------------------------------
# OUTPUT
#-------------------------------------------      
output:
  - platform: ledc
    pin: $beeper_ledc
    id: rtttl_out

#-------------------------------------------
# RTTTL
#-------------------------------------------
rtttl:
  output: rtttl_out
  gain: 60%

#-------------------------------------------
# SWITCH
#-------------------------------------------
switch:
  - platform: template
    name: "Звук нажатие клавиш"
    optimistic: True
    id: sound
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:volume-off
