esphome:
  name: aqua
  friendly_name: AQUA

esp32:
  board: denky_d4
  flash_size: 8MB
  framework:
    type: arduino
    
#-------------------------------------------
# PSRAM
#-------------------------------------------
psram:
  mode: quad
  speed: 80MHz

# Enable logging
logger:

# Enable Home Assistant API
api:
  actions:
    - action: rtttl_play
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

#-------------------------------------------
# PACKAGES
#-------------------------------------------
packages:
  web: !include included/web.yaml

#-------------------------------------------
# TOUCH
#-------------------------------------------
esp32_touch:
#  setup_mode: true

binary_sensor:

  - platform: esp32_touch
    name: "Левая кнопка"
    id: left_touch
    pin: GPIO15
    threshold: 1050

  - platform: esp32_touch
    name: "Правая кнопка"
    id: right_touch
    pin: GPIO2
    threshold: 1100

  - platform: gpio
    pin:
      number: GPIO33
    id: "input"
    name: "Вход"

switch:
  - platform: gpio
    name: "Реле 1"
    pin: GPIO3
    id: relay1    

  - platform: gpio
    name: "Реле 2"
    pin: GPIO19
    id: relay2      

#-------------------------------------------
# OUTPUT
#-------------------------------------------      
output:
  - platform: ledc
    pin: GPIO25
    id: rtttl_out
    
rtttl:
  output: rtttl_out

light:

  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO26
    num_leds: 5
    rmt_channel: 0
    chipset: WS2812
    name: "My Light"
    id: led_ww