#-------------------------------------------
# Add yaml 
#packages:
#  1in: !include 
#    file: packages/lume/1in.yaml
#    vars:
#      one_pin: GPIO33
# and copy file esphome/packages/lume

#-------------------------------------------
# BINARY SENSOR
#-------------------------------------------
binary_sensor:
  - platform: gpio
    pin:
      number: $one_pin
      inverted: true
    id: "input1"
    name: "${name} Вход 1"
    icon: mdi:inbox-arrow-down-outline
    on_press:
      then:
        - lambda: |-
            int8_t act_in1 = id(g_in1);
            switch(act_in1) {
              case 0: break;
              case 1: id(light_dimmer1).turn_on().set_brightness(1.0).perform(); break;
              case 2 ... 4: id(light_dimmer1).toggle().perform(); break;

            }
    on_release: 
      then:
        - lambda: |-
            int8_t act_in1 = id(g_in1);
            switch(act_in1) {
              case 0: break;
              case 1: id(light_dimmer1).turn_off().set_brightness(1.0).perform(); break;
              case 2 ... 43: id(light_dimmer1).toggle().perform(); break;
            }

#-------------------------------------------
# SELECT
#-------------------------------------------
select:
  - platform: template
    name: "Тип внешнего выключателя 1"
    entity_category: config
    id: type_external_1
    icon: mdi:dip-switch
    options:
      - "Не использовать"              
      - "Стандартный"             
      - "Проходной"
      - "Без фиксации замыкающий"             
      - "Без фиксации размыкающий"                
    initial_option: "Не использовать"
    optimistic: true
    on_value:
      then:
        - lambda: |-
            id(g_in1) = (i);
        - logger.log:
            format: "IN1 option: %s (%d)"
            args: ["x.c_str()", "i"]


#-------------------------------------------
# GLOBALS
#-------------------------------------------            
globals:
  - id: g_in1
    type: int
    restore_value: no
    initial_value: '0'

