# -------------------------------------------
#  Add yaml and copy file esphome/packages/sensor/
#packages:
#  bh: !include 
#    file: packages/sensor/bh1750.yaml
#    vars:
#      id_bh: light_bh
# -------------------------------------------

#-------------------------------------------
# SENSOR BH1750
#-------------------------------------------
sensor:
  - platform: bh1750
    name: "${name} Illuminance"
    id: ${id_bh}
    address: 0x23
    update_interval: 5s
    icon: mdi:brightness-5